### ISSUE TITLE
TOR Support?

### ISSUE THREAD

**Issue by btchans** [nbd-wtf/satdress#45]
does satdress support tor?

clearnet setups work
but when i try to setup a onionservice it gives me:
```
couldn't make an invoice with the given data: call to lnbits failed (501): <html>
<head>
<title>This is a SOCKS Proxy, Not An HTTP Proxy</title>
</head>
<body>
<h1>This is a SOCKs proxy, not an HTTP proxy.</h1>
<p>
It appears you have configured your web browser to use this Tor port as
an HTTP proxy.
</p><p>
This is not correct: This port is configured as a SOCKS proxy, no
```

this is my docker-compose 
```
version: "3.7"

services:
  satdress:
    build: .
    container_name: satdress
    restart: always
    environment:
      - PORT=17422
      - DOMAIN=xyzui.com
      - SECRET=qsssdfdxyzjdhokidfdfdwaslpoz
      - SITE_OWNER_URL=https://t.me/fdf
      - SITE_OWNER_NAME=@dfdf
      - SITE_NAME=Satdress
      - TOR_PROXY_URL=socks5h://tor:9050
    ports:
      - 17422:17422
    volumes:
      - satdressData:/satdress.com
    networks:
      - proxy

  tor:
    container_name: tor
    image: dperson/torproxy
    ports:
      - 9050:9050
    restart: always
    ports:
      - 9050:9050
    networks:
      - proxy

networks:
  proxy:
    name: root_proxy
    external: true
volumes:
  satdressData:
    name: satdressData
```
